const petsSampleData = [
  {
    imageURL: "https://a-z-animals.com/media/2022/07/Best-dog-products-on-prime-day-header-1536x1024.jpg",
    title: "Labrador looking for rehome.",
    prevPrice: "LKR 40,000",
    newPrice: "25,000",
    color: "orange",
    breed: "labrador",
    characteristic: "playful",
    age: "1",
  }, 
  {
    imageURL: "https://www.dutch.com/cdn/shop/articles/shutterstock_538333303.jpg?v=1683242960&width=900",
    title: "Cute Persian Cat for sale!",
    prevPrice: "LKR 45,000",
    newPrice: "40,000",
    color: "white",
    breed: "persian",
    characteristic: "calm",
    age: "1",
  },
  {
    imageURL: "https://i.ebayimg.com/images/g/EP8AAOSwDt1fRDxD/s-l1200.jpg",
    title: "White Goldfish FOR SALE!",
    prevPrice: "LKR 300",
    newPrice: "100",
    color: "white",
    breed: "goldfish",
    characteristic: "peaceful",
    age: "3 months",
  },
  {
    imageURL: "https://upload.wikimedia.org/wikipedia/commons/1/16/Female_Black_Labrador_Retriever.jpg",
    title: "Cute Labrador dog for sale.",
    prevPrice: "LKR 50,000",
    newPrice: "40,000",
    color: "black",
    breed: "labrador",
    characteristic: "playful",
    age: "1",
  },
  {
    imageURL: "https://everybunnywelcome.com/wp-content/uploads/2022/09/orange-holland-lop-1024x682.jpg",
    title: "Cute bunny looking for a home!",
    prevPrice: "LKR 35,0000",
    newPrice: "25,000",
    color: "orange",
    breed: "hollandlop",
    characteristic: "playful",
    age: "0",
  },
  {
    imageURL: "https://thelabradorfamily.com/wp-content/uploads/2022/03/Chocolate-Labrador-1.jpg",
    title: "'Health Checked'❤‍🩹 and 'Vaccinated'💉 Labrador Dog",
    prevPrice: "LKR 40,000",
    newPrice: "35,000",
    color: "chocolate",
    breed: "labrador",
    characteristic: "playful",
    age: "1",
  },
  {
    imageURL: "https://petkeen.com/wp-content/uploads/2022/08/A-happy-Golden-Retriever-adult-male-dog-relaxing-in-a-park_Neelsky_Shutterstock.jpg",
    title: "Top quality Golden Retriever for sale!",
    prevPrice: "LKR 60,000",
    newPrice: "50,000",
    color: "orange",
    breed: "goldenretriever",
    characteristic: "playful",
    age: "1",
  },
  {
    imageURL: "https://puppyintraining.com/wp-content/uploads/block-head-english-cream-retriever.jpg",
    title: "Golden Retriever - 1 year old dog for sale",
    prevPrice: "LKR 60,000",
    newPrice: "45,000",
    color: "cream",
    breed: "goldenretriever",
    characteristic: "playful",
    age: "1",
  },
];

export default petsSampleData;